import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { Check, ArrowRight } from 'lucide-react';
import { Link } from '@/i18n/navigation';
import type { AppLocale } from '@/i18n/routing';
import { getMarketSoftCopy, getPackage } from '@/lib/marketsoft-content';
import { buildMetadata } from '@/lib/seo';
type Props={params:Promise<{locale:AppLocale;packageSlug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{locale,packageSlug}=await params;const pkg=getPackage(locale,packageSlug);if(!pkg)return{};return buildMetadata(locale,{pathname:'/packages/[packageSlug]',params:{packageSlug}},`${pkg.name} | MarketSoft`,pkg.target)}
export default async function PackageDetail({params}:Props){const{locale,packageSlug}=await params;const c=getMarketSoftCopy(locale);const pkg=getPackage(locale,packageSlug);if(!pkg)notFound();return <div className="ms-page"><section className="ms-inner-hero"><div className="site-container ms-package-hero"><div><span className="ms-eyebrow">MarketSoft Package</span><h1>{pkg.name}</h1><p>{pkg.target}</p><div className="ms-package-hero__meta"><strong>{pkg.price}</strong><span>{pkg.delay}</span></div><div className="ms-actions"><Link href={{pathname:'/order',query:{package:pkg.slug,intent:'order'}}} className="ms-button ms-button--primary">{c.packageActions.order}<ArrowRight size={16}/></Link></div></div></div></section><section className="ms-section"><div className="site-container ms-detail-layout"><div><h2>{locale==='fr'?'Pour qui ?':locale==='ar'?'لمن؟':'Who is it for?'}</h2><ul className="ms-check-list">{pkg.audiences.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></div><div><h2>{locale==='fr'?'Ce que vous pouvez faire':locale==='ar'?'ما الذي يمكنك فعله':'What you can do'}</h2><ul className="ms-check-list">{pkg.outcomes.map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul></div></div></section><section className="ms-section ms-section--dark"><div className="site-container"><div className="ms-section-head"><h2>{locale==='fr'?'Ce qui est inclus':locale==='ar'?'ما هو مشمول':'What is included'}</h2></div><div className="ms-module-grid">{pkg.modules.map(m=><article key={m.title}><h3>{m.title}</h3><ul>{m.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section><section className="ms-section"><div className="site-container ms-options"><h2>{locale==='fr'?'Options & accompagnement':locale==='ar'?'الخيارات والدعم':'Options & support'}</h2>{pkg.options.map(x=><p key={x}>{x}</p>)}</div></section></div>}
